"use server";
import {revalidatePath} from "next/cache";import {requireAdmin} from "@/lib/auth";import {prisma} from "@/lib/prisma";
import {deleteCounsellorImage,deleteGalleryMedia,deletePaymentProof,deletePublicImage} from "@/lib/media-storage";
export type DeleteState={error?:string;success?:string}|null;
const id=(f:FormData)=>String(f.get("id")||"");
export async function deleteCounsellor(_:DeleteState,f:FormData):Promise<DeleteState>{await requireAdmin();const recordId=id(f),c=await prisma.counsellor.findUnique({where:{id:recordId},include:{_count:{select:{appointments:true}}}});if(!c)return{error:"Counsellor was not found."};if(c._count.appointments)return{error:"This counsellor has existing booking records and cannot be permanently deleted. You can deactivate the counsellor instead."};await prisma.$transaction([prisma.counsellorservice.deleteMany({where:{counsellorId:recordId}}),prisma.availability.deleteMany({where:{counsellorId:recordId}}),prisma.blockedDate.deleteMany({where:{counsellorId:recordId}}),prisma.counsellor.delete({where:{id:recordId}})]);if(c.photo){const used=await prisma.counsellor.count({where:{photo:c.photo}});if(!used)await deleteCounsellorImage(c.photo)}revalidatePath("/");revalidatePath("/admin/counsellors");revalidatePath("/counsellors");revalidatePath(`/counsellors/${c.slug}`);return{success:`${c.name} was deleted.`}}
export async function deleteService(_:DeleteState,f:FormData):Promise<DeleteState>{await requireAdmin();const recordId=id(f),s=await prisma.service.findUnique({where:{id:recordId},include:{_count:{select:{appointments:true}}}});if(!s)return{error:"Service was not found."};if(s._count.appointments)return{error:"This service has existing booking records and cannot be permanently deleted. Deactivate it instead."};await prisma.$transaction([prisma.counsellorservice.deleteMany({where:{serviceId:recordId}}),prisma.service.delete({where:{id:recordId}})]);revalidatePath("/admin/services");revalidatePath("/services");return{success:`${s.name} was deleted.`}}
export async function deleteBooking(_:DeleteState,f:FormData):Promise<DeleteState>{await requireAdmin();const recordId=id(f),existing=await prisma.appointment.findUnique({where:{id:recordId},include:{payments:{select:{proofImagePath:true}}}});if(!existing)return{error:"Booking was not found."};const b=await prisma.appointment.delete({where:{id:recordId}});await Promise.all(existing.payments.map(payment=>deletePaymentProof(payment.proofImagePath)));revalidatePath("/admin/bookings");return{success:`Booking ${b.bookingNumber} was deleted.`}}
export async function deleteEnquiry(_:DeleteState,f:FormData):Promise<DeleteState>{await requireAdmin();await prisma.contactEnquiry.delete({where:{id:id(f)}});revalidatePath("/admin/enquiries");return{success:"Enquiry was deleted."}}
export async function deleteResource(_:DeleteState,f:FormData):Promise<DeleteState>{await requireAdmin();const r=await prisma.resource.delete({where:{id:id(f)}});revalidatePath("/admin/resources");revalidatePath("/resources");return{success:`${r.title} was deleted.`}}
export async function deleteFaq(_:DeleteState,f:FormData):Promise<DeleteState>{await requireAdmin();await prisma.fAQ.delete({where:{id:id(f)}});revalidatePath("/admin/faqs");return{success:"FAQ was deleted."}}
export async function deleteTestimonial(_:DeleteState,f:FormData):Promise<DeleteState>{await requireAdmin();await prisma.testimonial.delete({where:{id:id(f)}});revalidatePath("/admin/testimonials");return{success:"Testimonial was deleted."}}
export async function deleteAvailability(_:DeleteState,f:FormData):Promise<DeleteState>{await requireAdmin();await prisma.availability.delete({where:{id:id(f)}});revalidatePath("/admin/availability");return{success:"Availability was deleted."}}
export async function deleteMedia(_:DeleteState,f:FormData):Promise<DeleteState>{await requireAdmin();const m=await prisma.media.delete({where:{id:id(f)}});if(!m.url.startsWith("/uploads/"))await deletePublicImage(m.url);revalidatePath("/admin/media");return{success:"Media was deleted."}}
export async function deleteGallery(_:DeleteState,f:FormData):Promise<DeleteState>{await requireAdmin();const recordId=id(f),item=await prisma.galleryItem.findUnique({where:{id:recordId}});if(!item)return{error:"Gallery item was not found."};await prisma.galleryItem.delete({where:{id:recordId}});if(item.url)await deleteGalleryMedia(item.url);revalidatePath("/admin/gallery");revalidatePath("/gallery");return{success:"Gallery item was deleted."}}

