import Link from "next/link"; import { ArrowRight, Baby, BriefcaseBusiness, CheckCircle2, Ear, GraduationCap, HandHeart, HeartHandshake, LockKeyhole, Map, MessageCircleHeart, Ribbon, Scale, ShieldCheck, Sparkles, UserRound, UsersRound } from "lucide-react"; import { Breadcrumb, Button, SectionTitle } from "@/components/ui";
export const metadata = { title: "About" };
const values = [[Ear, "Empathy", "We listen before we advise."], [LockKeyhole, "Confidentiality", "Privacy and trust are central to meaningful psychological care."], [Sparkles, "Individuality", "There is no one-size-fits-all path to wellbeing."], [Scale, "Professional Integrity", "Care should be thoughtful, ethical and evidence-informed."], [HandHeart, "Respect", "Every person's experience, identity and context deserves consideration."], [HeartHandshake, "Collaboration", "Therapy works best when care is built together, not imposed."]] as const;
const approach = [[Ear, "Listen carefully", "Begin with attentive, unhurried conversation."], [Map, "Understand context", "Consider the experiences and relationships around the concern."], [MessageCircleHeart, "Build a shared plan", "Agree on goals and an approach that feels appropriate."], [Sparkles, "Support meaningful progress", "Review, adapt and build changes that can be sustained."]] as const;
const expectations = ["Evidence-informed psychological approaches", "Respect for individual identity and lived experience", "Privacy-conscious and ethically grounded care", "Collaboration instead of one-size-fits-all advice", "Clear and considerate communication", "Care tailored to your needs"];
const reasons = [[Ear, "Thoughtful Listening", "We begin by understanding your experience before deciding what support may help."], [ShieldCheck, "Qualified Professionals", "Care is delivered by appropriately trained psychological professionals."], [MessageCircleHeart, "Flexible Access", "Support can be accessed online or in-person where available."], [HeartHandshake, "Continuity of Care", "The focus is not only immediate relief, but healthier long-term patterns and wellbeing."]] as const;
const audiences = [[UserRound, "Individuals"], [HeartHandshake, "Couples"], [UsersRound, "Families"], [Baby, "Children"], [UsersRound, "Teenagers"], [GraduationCap, "Students"], [BriefcaseBusiness, "Working Professionals"], [Ribbon, "People navigating serious illness and cancer-related emotional challenges"]] as const;
const oncology = ["Coping with diagnosis", "Treatment-related stress", "Fear and uncertainty", "Family and caregiver support", "Emotional adjustment", "Survivorship and life after treatment"];
export default function About() {
  return <div className="about-page">
    <section className="about-hero"><span className="about-hero-orbit" aria-hidden="true" /><div className="container"><Breadcrumb current="About" /><p className="eyebrow">About Ulam Seyal</p><h1>Understanding minds.<br /></h1><p>Ulam Seyal is a psychology, counselling and psycho-oncology care platform built around thoughtful listening, professional integrity and support that respects each person&apos;s individual context.</p></div></section>
    <section className="about-section about-story"><div className="container about-story-grid"><div><p className="eyebrow">Our Story</p><h2>Care begins with being heard.</h2><div className="story-mark" aria-hidden="true"><Ear /><span>Listen first.<br />Understand fully.</span></div></div><div className="about-prose"><p className="story-lead">Ulam Seyal was created with a simple belief: psychological care should feel human, respectful and accessible.</p><p>Too often, people delay seeking support because therapy can feel intimidating, impersonal or difficult to navigate. Ulam Seyal aims to make that first step easier by creating a space where individuals can speak openly, understand themselves better and receive professional guidance without judgement.</p><p>Our work brings together psychological wellness, counselling and psycho-oncology support, with care shaped around the needs, experiences and circumstances of each person.</p></div></div></section>
    <section className="about-section vision-mission"><div className="container vision-grid"><article className="vision-card"><span>01</span><p className="eyebrow">Our Vision</p><h2>A world where seeking psychological support feels normal, accessible and respected.</h2><p>We envision mental healthcare as an everyday part of wellbeing — where individuals and families can seek professional support early, openly and without stigma.</p></article><article className="mission-card"><span>02</span><p className="eyebrow">Our Mission</p><h2>To make thoughtful, professional psychological care easier to access and easier to trust.</h2><p>Our mission is to provide compassionate, evidence-informed psychological support while respecting privacy, individuality and the lived experience of every person we work with.</p></article></div></section>
    <section className="about-section about-values"><div className="container"><SectionTitle eyebrow="What guides us" title="Our values shape every conversation." /><div className="value-grid">{values.map(([Icon, title, text]) => <article key={title}><span><Icon /></span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="about-section approach-section"><div className="container"><div className="approach-intro"><SectionTitle eyebrow="Our approach" title="Care shaped around the whole person." /><div className="about-prose"><p>Mental health concerns rarely exist in isolation. Personal history, relationships, work, physical health, identity, family dynamics and life experiences can all influence emotional wellbeing.</p><p>Our approach begins with understanding the individual rather than reducing them to a label or symptom. Through assessment, conversation and collaborative planning, care is tailored to what feels appropriate, useful and sustainable.</p></div></div><div className="approach-steps">{approach.map(([Icon, title, text], index) => <article key={title}><span className="step-number">0{index + 1}</span><Icon /><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="about-section expect-section"><div className="container expect-panel"><div><p className="eyebrow">Your care experience</p><h2>What you can expect</h2><p>Professional support should feel clear, respectful and grounded in a genuine understanding of you.</p><Button href="/book-consultation">Book a Consultation</Button></div><div className="expect-list">{expectations.map(item => <p key={item}><CheckCircle2 />{item}</p>)}</div></div></section>
    <section className="about-section why-section"><div className="container"><SectionTitle eyebrow="Why Ulam Seyal" title="Professional care. Human connection." /><div className="why-grid">{reasons.map(([Icon, title, text]) => <article key={title}><Icon /><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="about-section support-section"><div className="container"><SectionTitle eyebrow="Who we support" title="Support for different stages of life." text="Care can respond to different relationships, responsibilities and moments of change." /><div className="audience-grid">{audiences.map(([Icon, label]) => <article key={label}><Icon /><span>{label}</span></article>)}</div></div></section>
    <section className="about-section oncology-section"><div className="container oncology-grid"><div><p className="eyebrow">Psycho-oncology care</p><h2>Psychological support alongside the cancer journey.</h2><p>A cancer diagnosis can affect emotional wellbeing, relationships, family life and a person&apos;s sense of control. Psycho-oncology support focuses on the psychological and emotional needs that may arise during diagnosis, treatment, recovery and caregiving.</p><small><ShieldCheck />Psycho-oncology support complements medical care and does not replace treatment from oncology professionals.</small></div><div className="oncology-points">{oncology.map(item => <p key={item}><CheckCircle2 />{item}</p>)}</div></div></section>
    <section className="about-final"><div className="container"><div><p className="eyebrow">Not sure where to begin?</p><h2>A simple conversation can help clarify your next step.</h2><p>Tell us what you&apos;re looking for and our team can help you understand which service or professional may be appropriate.</p></div><div className="about-final-actions"><Button href="/book-consultation">Book a Consultation</Button><Link className="about-secondary" href="/contact">Talk to Our Care Team <ArrowRight /></Link></div></div></section>
  </div>
}
