"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { Search, X } from "lucide-react";
import { concerns, resources, services, specialists } from "@/data/site";
export function SearchModal({open,onClose}:{open:boolean;onClose:()=>void}){ const [q,setQ]=useState(""); const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{if(open)setTimeout(()=>input.current?.focus(),50); const esc=(e:KeyboardEvent)=>e.key==="Escape"&&onClose();document.addEventListener("keydown",esc);return()=>document.removeEventListener("keydown",esc)},[open,onClose]); if(!open)return null;
 const all=[...services.map(x=>({title:x.title,kind:"Service",href:`/services/${x.slug}`})),...concerns.map(x=>({title:x[1],kind:"Mental health",href:`/mental-health/${x[0]}`})),...specialists.map(x=>({title:x.name,kind:x.role,href:`/specialists/${x.slug}`})),...resources.map(x=>({title:x[2],kind:"Resource",href:`/resources/${x[0]}`}))]; const result=q.length>1?all.filter(x=>x.title.toLowerCase().includes(q.toLowerCase())).slice(0,8):[];
 return <div role="dialog" aria-modal="true" aria-label="Site search" className="fixed inset-0 z-[90] bg-[#102d29]/80 p-4 backdrop-blur-sm"><div className="mx-auto mt-[8vh] max-w-3xl bg-[#fffdf9] shadow-2xl"><div className="flex items-center gap-3 border-b p-5"><Search/><input ref={input} value={q} onChange={e=>setQ(e.target.value)} placeholder="Search support, services, specialists or guides" aria-label="Search query" className="w-full bg-transparent text-lg outline-none"/><button onClick={onClose} aria-label="Close search"><X/></button></div><div className="max-h-[60vh] min-h-48 overflow-auto p-4">{q.length<2?<p className="p-6 text-center text-sm text-[#657974]">Begin typing to explore Ulam Seyal.</p>:result.length?result.map(x=><Link onClick={onClose} href={x.href} key={x.href} className="flex items-center justify-between border-b border-[#e4e9e6] px-4 py-4 hover:bg-[#eef4ef]"><span>{x.title}</span><span className="text-[10px] font-bold uppercase tracking-widest text-[#779088]">{x.kind}</span></Link>):<p className="p-6 text-center text-sm">No matching results. Try a broader phrase.</p>}</div></div></div> }
