"use client";
import Image from "next/image";
import {useState} from "react";
import {X} from "lucide-react";
import {rejectPayment,verifyPayment} from "@/app/admin/(protected)/booking-actions";

export function PaymentProof({src,bookingNumber}:{src:string;bookingNumber:string}){const[open,setOpen]=useState(false);return <><button type="button" className="payment-proof-thumb" onClick={()=>setOpen(true)}><Image src={src} width={200} height={160} alt={`Payment proof for ${bookingNumber}`}/><span>View larger</span></button><a className="admin-proof-link" href={src} target="_blank" rel="noreferrer">Open Full Image ↗</a>{open&&<div className="proof-lightbox" role="dialog" aria-modal="true" aria-label="Payment proof preview" onClick={()=>setOpen(false)}><button type="button" aria-label="Close preview"><X/></button><Image src={src} width={1000} height={800} alt={`Payment proof for ${bookingNumber}`} onClick={event=>event.stopPropagation()}/></div>}</>}

export function PaymentReviewActions({appointmentId,paymentId,bookingNumber,amount}:{appointmentId:string;paymentId:string;bookingNumber:string;amount:string}){const[rejecting,setRejecting]=useState(false);return <div className="payment-review-actions"><form action={verifyPayment} onSubmit={event=>{if(!window.confirm(`Verify ${amount} payment for booking ${bookingNumber}?`))event.preventDefault()}}><input type="hidden" name="appointmentId" value={appointmentId}/><input type="hidden" name="paymentId" value={paymentId}/><button className="admin-primary">Verify Payment</button></form><button type="button" className="admin-danger" onClick={()=>setRejecting(true)}>Reject Payment</button>{rejecting&&<form action={rejectPayment} className="payment-reject-form"><input type="hidden" name="appointmentId" value={appointmentId}/><input type="hidden" name="paymentId" value={paymentId}/><label>Rejection Reason<textarea name="rejectionReason" minLength={5} rows={3} required placeholder="Explain why this payment could not be verified"/></label><div><button type="button" onClick={()=>setRejecting(false)}>Cancel</button><button className="admin-danger">Confirm Rejection</button></div></form>}</div>}
